import { toPascalCase } from '@/utils/helpers'

export type CompanyData = {
  company: string
  symbol: string
  price: string
  change: string
  volume: string
  marketCap: string
  rating: string
  status: 'Bullish' | 'Bearish'
  sector: string
  industry: string
  employees: string
  founded: string
  peRatio: string
  dividend: string
  high52W: string
  low52W: string
  ceo: string
}

export const columns = [
  { title: 'Company', data: 'company', width: '123px' },
  { title: 'Symbol', data: 'symbol' },
  {
    title: 'Price',
    data: 'price',
    render: (data: number) => `${data}`,
    className: 'text-start',
  },
  {
    title: 'Change',
    data: 'change',
    render: (data: number) => `${data}%`,
    className: 'text-start',
  },
  { title: 'Volume', data: 'volume', className: 'text-start' },
  {
    title: 'Market Cap',
    data: 'marketCap',
    render: (data: string) => `${data}`,
  },
  {
    title: 'Rating',
    data: 'rating',
    render: (data: number) => `${data} ★`,
  },
  {
    title: 'Status',
    data: 'status',
    render: (data: string) => {
      const badgeClass = data.toLowerCase() === 'bullish' ? 'success' : 'danger'
      return `<span class="badge badge-soft-${badgeClass}">${toPascalCase(data)}</span>`
    },
  },
  { title: 'Sector', data: 'sector', width: '153px' },
  { title: 'Industry', data: 'industry', width: '135px' },
  { title: 'Employees', data: 'employees' },
  { title: 'Founded', data: 'founded' },
  { title: 'P/E Ratio', data: 'peRatio' },
  { title: 'Dividend', data: 'dividend' },
  { title: '52W High', data: 'high52W' },
  { title: '52W Low', data: 'low52W' },
  { title: 'CEO', data: 'ceo', width: '123px' },
]

export const companies: CompanyData[] = [
  {
    company: 'Apple Inc.',
    symbol: 'AAPL',
    price: '$2109.53',
    change: '-0.42%',
    volume: '48,374,838',
    marketCap: '$53.59B',
    rating: '4.7 ★',
    status: 'Bearish',
    sector: 'Technology',
    industry: 'Consumer Electronics',
    employees: '160,000',
    founded: '1976',
    peRatio: '28.5',
    dividend: '0.65%',
    high52W: '$2150',
    low52W: '$1200',
    ceo: 'Tim Cook',
  },
  {
    company: 'Microsoft Corp.',
    symbol: 'MSFT',
    price: '$450.98',
    change: '-2.04%',
    volume: '26,604,335',
    marketCap: '$927.77B',
    rating: '3.8 ★',
    status: 'Bearish',
    sector: 'Technology',
    industry: 'Software',
    employees: '221,000',
    founded: '1975',
    peRatio: '35.1',
    dividend: '0.82%',
    high52W: '$480',
    low52W: '$320',
    ceo: 'Satya Nadella',
  },
  {
    company: 'Amazon.com Inc.',
    symbol: 'AMZN',
    price: '$127.54',
    change: '+1.12%',
    volume: '36,992,200',
    marketCap: '$1.24T',
    rating: '4.5 ★',
    status: 'Bullish',
    sector: 'Consumer Discretionary',
    industry: 'E-Commerce',
    employees: '1,540,000',
    founded: '1994',
    peRatio: '61.4',
    dividend: '0%',
    high52W: '$145',
    low52W: '$87',
    ceo: 'Andy Jassy',
  },
  {
    company: 'Alphabet Inc.',
    symbol: 'GOOGL',
    price: '$138.34',
    change: '+0.77%',
    volume: '25,105,431',
    marketCap: '$1.74T',
    rating: '4.6 ★',
    status: 'Bullish',
    sector: 'Communication Services',
    industry: 'Internet Content',
    employees: '190,711',
    founded: '1998',
    peRatio: '29.8',
    dividend: '0%',
    high52W: '$145',
    low52W: '$95',
    ceo: 'Sundar Pichai',
  },
  {
    company: 'Meta Platforms Inc.',
    symbol: 'META',
    price: '$332.25',
    change: '-0.12%',
    volume: '14,837,201',
    marketCap: '$948.33B',
    rating: '4.1 ★',
    status: 'Bearish',
    sector: 'Communication Services',
    industry: 'Social Media',
    employees: '71,970',
    founded: '2004',
    peRatio: '24.2',
    dividend: '0%',
    high52W: '$360',
    low52W: '$255',
    ceo: 'Mark Zuckerberg',
  },
  {
    company: 'Tesla Inc.',
    symbol: 'TSLA',
    price: '$245.57',
    change: '-3.45%',
    volume: '22,634,342',
    marketCap: '$778.21B',
    rating: '3.7 ★',
    status: 'Bearish',
    sector: 'Consumer Discretionary',
    industry: 'Automobiles',
    employees: '140,473',
    founded: '2003',
    peRatio: '72.3',
    dividend: '0%',
    high52W: '$310',
    low52W: '$190',
    ceo: 'Elon Musk',
  },
  {
    company: 'NVIDIA Corp.',
    symbol: 'NVDA',
    price: '$789.25',
    change: '+2.89%',
    volume: '38,251,124',
    marketCap: '$1.94T',
    rating: '4.9 ★',
    status: 'Bullish',
    sector: 'Technology',
    industry: 'Semiconductors',
    employees: '22,473',
    founded: '1993',
    peRatio: '92.4',
    dividend: '0.06%',
    high52W: '$825',
    low52W: '$375',
    ceo: 'Jensen Huang',
  },
  {
    company: 'Netflix Inc.',
    symbol: 'NFLX',
    price: '$442.35',
    change: '+1.24%',
    volume: '4,350,932',
    marketCap: '$197.31B',
    rating: '4.2 ★',
    status: 'Bullish',
    sector: 'Communication Services',
    industry: 'Streaming',
    employees: '12,800',
    founded: '1997',
    peRatio: '44.8',
    dividend: '0%',
    high52W: '$460',
    low52W: '$300',
    ceo: 'Ted Sarandos',
  },
  {
    company: 'Adobe Inc.',
    symbol: 'ADBE',
    price: '$589.23',
    change: '-1.17%',
    volume: '2,589,123',
    marketCap: '$278.12B',
    rating: '4.6 ★',
    status: 'Bearish',
    sector: 'Technology',
    industry: 'Software',
    employees: '29,239',
    founded: '1982',
    peRatio: '48.5',
    dividend: '0%',
    high52W: '$610',
    low52W: '$470',
    ceo: 'Shantanu Narayen',
  },
  {
    company: 'Intel Corp.',
    symbol: 'INTC',
    price: '$35.23',
    change: '-0.98%',
    volume: '18,231,004',
    marketCap: '$147.89B',
    rating: '3.2 ★',
    status: 'Bearish',
    sector: 'Technology',
    industry: 'Semiconductors',
    employees: '121,100',
    founded: '1968',
    peRatio: '15.1',
    dividend: '1.3%',
    high52W: '$42',
    low52W: '$28',
    ceo: 'Pat Gelsinger',
  },
  {
    company: 'PayPal Holdings',
    symbol: 'PYPL',
    price: '$63.12',
    change: '+0.82%',
    volume: '9,721,222',
    marketCap: '$74.23B',
    rating: '3.4 ★',
    status: 'Bullish',
    sector: 'Financials',
    industry: 'Digital Payments',
    employees: '29,900',
    founded: '1998',
    peRatio: '18.6',
    dividend: '0%',
    high52W: '$88',
    low52W: '$56',
    ceo: 'Alex Chriss',
  },
  {
    company: 'Salesforce Inc.',
    symbol: 'CRM',
    price: '$217.88',
    change: '+0.44%',
    volume: '6,231,654',
    marketCap: '$213.43B',
    rating: '4.3 ★',
    status: 'Bullish',
    sector: 'Technology',
    industry: 'CRM Software',
    employees: '79,390',
    founded: '1999',
    peRatio: '33.2',
    dividend: '0%',
    high52W: '$225',
    low52W: '$170',
    ceo: 'Marc Benioff',
  },
  {
    company: 'IBM',
    symbol: 'IBM',
    price: '$139.24',
    change: '-0.52%',
    volume: '4,893,014',
    marketCap: '$126.48B',
    rating: '3.6 ★',
    status: 'Bearish',
    sector: 'Technology',
    industry: 'IT Services',
    employees: '288,300',
    founded: '1911',
    peRatio: '14.8',
    dividend: '5.2%',
    high52W: '$150',
    low52W: '$115',
    ceo: 'Arvind Krishna',
  },
  {
    company: 'Oracle Corp.',
    symbol: 'ORCL',
    price: '$123.78',
    change: '+0.65%',
    volume: '7,653,241',
    marketCap: '$331.12B',
    rating: '4.0 ★',
    status: 'Bullish',
    sector: 'Technology',
    industry: 'Enterprise Software',
    employees: '143,000',
    founded: '1977',
    peRatio: '18.2',
    dividend: '1.8%',
    high52W: '$130',
    low52W: '$98',
    ceo: 'Larry Ellison',
  },
  {
    company: 'Qualcomm',
    symbol: 'QCOM',
    price: '$115.56',
    change: '-1.01%',
    volume: '6,712,000',
    marketCap: '$129.42B',
    rating: '3.9 ★',
    status: 'Bearish',
    sector: 'Technology',
    industry: 'Semiconductors',
    employees: '51,000',
    founded: '1985',
    peRatio: '14.2',
    dividend: '2.2%',
    high52W: '$125',
    low52W: '$100',
    ceo: 'Cristiano Amon',
  },
  {
    company: 'Zoom Video Comm.',
    symbol: 'ZM',
    price: '$69.87',
    change: '-0.88%',
    volume: '2,198,215',
    marketCap: '$20.98B',
    rating: '3.5 ★',
    status: 'Bearish',
    sector: 'Communication Services',
    industry: 'Video Conferencing',
    employees: '8,484',
    founded: '2011',
    peRatio: '32.7',
    dividend: '0%',
    high52W: '$92',
    low52W: '$60',
    ceo: 'Eric Yuan',
  },
  {
    company: 'Spotify',
    symbol: 'SPOT',
    price: '$158.32',
    change: '+1.11%',
    volume: '1,498,320',
    marketCap: '$30.13B',
    rating: '4.1 ★',
    status: 'Bullish',
    sector: 'Communication Services',
    industry: 'Music Streaming',
    employees: '9,094',
    founded: '2006',
    peRatio: '—',
    dividend: '0%',
    high52W: '$165',
    low52W: '$115',
    ceo: 'Daniel Ek',
  },
  {
    company: 'Uber Technologies',
    symbol: 'UBER',
    price: '$49.24',
    change: '+0.92%',
    volume: '8,812,444',
    marketCap: '$102.34B',
    rating: '3.7 ★',
    status: 'Bullish',
    sector: 'Technology',
    industry: 'Ride Hailing',
    employees: '32,800',
    founded: '2009',
    peRatio: '—',
    dividend: '0%',
    high52W: '$53',
    low52W: '$32',
    ceo: 'Dara Khosrowshahi',
  },
  {
    company: 'Shopify',
    symbol: 'SHOP',
    price: '$75.44',
    change: '-0.21%',
    volume: '3,223,544',
    marketCap: '$96.72B',
    rating: '4.3 ★',
    status: 'Bullish',
    sector: 'Technology',
    industry: 'E-Commerce',
    employees: '11,600',
    founded: '2006',
    peRatio: '—',
    dividend: '0%',
    high52W: '$80',
    low52W: '$45',
    ceo: 'Tobi Lütke',
  },
]
