// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: health.sql

package sqlcgen

import (
	"context"
)

const ping = `-- name: Ping :one
SELECT 1 AS ok
`

// Trivial connectivity probe; also keeps the sqlc toolchain exercised until
// the first real platform queries arrive (outbox, T-005).
func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, ping)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}
