type OptionType = {
  label: string
  value: string
}

export const basicOptions: OptionType[] = [
  { value: 'AK', label: 'Alaska' },
  { value: 'HI', label: 'Hawaii' },
  { value: 'CA', label: 'California' },
  { value: 'NV', label: 'Nevada' },
  { value: 'OR', label: 'Oregon' },
  { value: 'WA', label: 'Washington' },
  { value: 'AZ', label: 'Arizona' },
  { value: 'CO', label: 'Colorado' },
  { value: 'ID', label: 'Idaho' },
  { value: 'MT', label: 'Montana' },
  { value: 'NE', label: 'Nebraska' },
  { value: 'NM', label: 'New Mexico' },
  { value: 'ND', label: 'North Dakota' },
  { value: 'UT', label: 'Utah' },
  { value: 'WY', label: 'Wyoming' },
  { value: 'AL', label: 'Alabama' },
  { value: 'AR', label: 'Arkansas' },
  { value: 'IL', label: 'Illinois' },
  { value: 'IA', label: 'Iowa' },
  { value: 'KS', label: 'Kansas' },
  { value: 'KY', label: 'Kentucky' },
  { value: 'LA', label: 'Louisiana' },
  { value: 'MN', label: 'Minnesota' },
  { value: 'MS', label: 'Mississippi' },
  { value: 'MO', label: 'Missouri' },
  { value: 'OK', label: 'Oklahoma' },
  { value: 'SD', label: 'South Dakota' },
  { value: 'TX', label: 'Texas' },
  { value: 'TN', label: 'Tennessee' },
  { value: 'WI', label: 'Wisconsin' },
  { value: 'CT', label: 'Connecticut' },
  { value: 'DE', label: 'Delaware' },
  { value: 'FL', label: 'Florida' },
  { value: 'GA', label: 'Georgia' },
  { value: 'IN', label: 'Indiana' },
  { value: 'ME', label: 'Maine' },
  { value: 'MD', label: 'Maryland' },
  { value: 'MA', label: 'Massachusetts' },
  { value: 'MI', label: 'Michigan' },
  { value: 'NH', label: 'New Hampshire' },
  { value: 'NJ', label: 'New Jersey' },
  { value: 'NY', label: 'New York' },
  { value: 'NC', label: 'North Carolina' },
  { value: 'OH', label: 'Ohio' },
  { value: 'PA', label: 'Pennsylvania' },
  { value: 'RI', label: 'Rhode Island' },
  { value: 'SC', label: 'South Carolina' },
  { value: 'VT', label: 'Vermont' },
  { value: 'VA', label: 'Virginia' },
  { value: 'WV', label: 'West Virginia' },
]

export const groupedOptions = [
  {
    label: 'Alaskan/Hawaiian Time Zone',
    options: [
      { label: 'Alaska', value: 'AK' },
      { label: 'Manchester', value: 'Manchester' },
      { label: 'Hawaii', value: 'HI' },
    ],
  },
  {
    label: 'Pacific Time Zone',
    options: [
      { label: 'California', value: 'CA' },
      { label: 'Nevada', value: 'NV' },
      { label: 'Oregon', value: 'OR' },
      { label: 'Washington', value: 'WA' },
    ],
  },
  {
    label: 'Mountain Time Zone',
    options: [
      { label: 'Arizona', value: 'AZ' },
      { label: 'Colorado', value: 'CO' },
      { label: 'Idaho', value: 'ID' },
      { label: 'Montana', value: 'MT' },
      { label: 'Nebraska', value: 'NE' },
      { label: 'New Mexico', value: 'NM' },
      { label: 'North Dakota', value: 'ND' },
      { label: 'Utah', value: 'UT' },
      { label: 'Wyoming', value: 'WY' },
    ],
  },
  {
    label: 'Central Time Zone',
    options: [
      { label: 'Alabama', value: 'AL' },
      { label: 'Arkansas', value: 'AR' },
      { label: 'Illinois', value: 'IL' },
      { label: 'Iowa', value: 'IA' },
      { label: 'Kansas', value: 'KS' },
      { label: 'Kentucky', value: 'KY' },
      { label: 'Louisiana', value: 'LA' },
      { label: 'Minnesota', value: 'MN' },
      { label: 'Mississippi', value: 'MS' },
      { label: 'Missouri', value: 'MO' },
      { label: 'Oklahoma', value: 'OK' },
      { label: 'South Dakota', value: 'SD' },
      { label: 'Texas', value: 'TX' },
      { label: 'Tennessee', value: 'TN' },
      { label: 'Wisconsin', value: 'WI' },
    ],
  },
  {
    label: 'Eastern Time Zone',
    options: [
      { label: 'Connecticut', value: 'CT' },
      { label: 'Delaware', value: 'DE' },
      { label: 'Florida', value: 'FL' },
      { label: 'Georgia', value: 'GA' },
      { label: 'Indiana', value: 'IN' },
      { label: 'Maine', value: 'ME' },
      { label: 'Maryland', value: 'MD' },
      { label: 'Massachusetts', value: 'MA' },
      { label: 'Michigan', value: 'MI' },
      { label: 'New Hampshire', value: 'NH' },
      { label: 'New Jersey', value: 'NJ' },
      { label: 'New York', value: 'NY' },
      { label: 'North Carolina', value: 'NC' },
      { label: 'Ohio', value: 'OH' },
      { label: 'Pennsylvania', value: 'PA' },
      { label: 'Rhode Island', value: 'RI' },
      { label: 'South Carolina', value: 'SC' },
      { label: 'Vermont', value: 'VT' },
      { label: 'Virginia', value: 'VA' },
      { label: 'West Virginia', value: 'WV' },
    ],
  },
]
